apiVersion: v1
kind: Service
metadata:
    message: security-admin-api-service
    labels:
        app: security-admin-api
        tier: backend
spec:
    type: LoadBalancer
    ports:
    - port: 2222
    selector:
        app: security-admin-api
        tier: backend